CREATE TABLE CERTIFICADO (
    ID_CERTIFICADO INT AUTO_INCREMENT PRIMARY KEY,
    STATUS BOOLEAN DEFAULT TRUE,
    TEXTO VARCHAR(1000) NOT NULL,
    HORAS VARCHAR(10) DEFAULT '0',
    DATA_CONCLUSAO DATE NOT NULL,
    FK_USUARIO_ID_USUARIO INT NOT NULL
);

CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    STATUS BOOLEAN DEFAULT TRUE,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    ADMIN BOOLEAN DEFAULT FALSE,
    CONSTRAINT CHK_STATUS CHECK (STATUS IN (0, 1))
);

CREATE TABLE USUARIO_MODULO (
    ID_USUARIO_MODULO INT AUTO_INCREMENT PRIMARY KEY,
    STATUS BOOLEAN DEFAULT TRUE,
    APROVADO BOOLEAN DEFAULT FALSE,
    INICIADO BOOLEAN DEFAULT FALSE,
    NOTA_FINAL INTEGER DEFAULT 0 CHECK (NOTA_FINAL >= 0 AND NOTA_FINAL <= 100),
    FK_MODULO_ID_MODULO INT NOT NULL,
    FK_USUARIO_ID_USUARIO INT NOT NULL
);

CREATE TABLE MODULO (
    ID_MODULO INT AUTO_INCREMENT PRIMARY KEY,
    STATUS BOOLEAN DEFAULT TRUE,
    NOME VARCHAR(100) NOT NULL,
    PORCENTAGEM_NECESSARIA VARCHAR(10) DEFAULT '60',
    CONSTRAINT CHK_PORCENTAGEM CHECK (CAST(PORCENTAGEM_NECESSARIA AS DECIMAL) BETWEEN 0 AND 100)
);

CREATE TABLE ATIVIDADE (
    ID_ATIVIDADE INT AUTO_INCREMENT PRIMARY KEY,
    STATUS BOOLEAN DEFAULT TRUE,
    TEXTO VARCHAR(1000) NOT NULL,
    ACERTOS INT DEFAULT 0,
    ERROS INT DEFAULT 0,
    FK_MODULO_ID_MODULO INT NOT NULL
);

CREATE TABLE ALTERNATIVA (
    ID_ALTERNATIVA INT AUTO_INCREMENT PRIMARY KEY,
    STATUS BOOLEAN DEFAULT TRUE,
    TEXTO VARCHAR(1000) NOT NULL,
    RESPOSTA_CERTA BOOLEAN DEFAULT FALSE,
    FK_ATIVIDADE_ID_ATIVIDADE INT NOT NULL
);

ALTER TABLE CERTIFICADO ADD CONSTRAINT FK_CERTIFICADO_2
    FOREIGN KEY (FK_USUARIO_ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE;

ALTER TABLE USUARIO_MODULO ADD CONSTRAINT FK_USUARIO_MODULO_2
    FOREIGN KEY (FK_MODULO_ID_MODULO)
    REFERENCES MODULO(ID_MODULO) ON DELETE CASCADE;

ALTER TABLE USUARIO_MODULO ADD CONSTRAINT FK_USUARIO_MODULO_3
    FOREIGN KEY (FK_USUARIO_ID_USUARIO)
    REFERENCES USUARIO(ID_USUARIO) ON DELETE RESTRICT;

ALTER TABLE ATIVIDADE ADD CONSTRAINT FK_ATIVIDADE_2
    FOREIGN KEY (FK_MODULO_ID_MODULO)
    REFERENCES MODULO(ID_MODULO) ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE ALTERNATIVA ADD CONSTRAINT FK_ALTERNATIVA_2
    FOREIGN KEY (FK_ATIVIDADE_ID_ATIVIDADE)
    REFERENCES ATIVIDADE(ID_ATIVIDADE) ON DELETE CASCADE;